name: main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: make install
      - name: Lint
        run: make lint
      - name: Unit-tests
        run: make test
      - run: echo "🍏 This job's status is ${{ job.status }}."
